@ChatPlatform.Server_HostAddress = https://localhost:7004

POST {{ChatPlatform.Server_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "login": "testuser",
  "password": "TestPassword123"
}

###

POST {{ChatPlatform.Server_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "login": "testuser1",
  "password": "TestPassword123"
}